### ISSUE TITLE
Incorrect usage of == operator when comparing two string objects

### ISSUE THREAD

**Issue by testerktu** [povderktu/cofeemachinee#5]
File : DrinkSoldDetailsDto.java
Line : 31
Description : Using an `==` operator to compare two strings `(...product.getIdentifer() == ...product.getIdentifer())`

**Comment by povderktu** [comment]
Working on a fix right now. Updated version should be ready for testing soon. @testerktu

**Comment by testerktu** [comment]
Ran into some other new issues while testing the updated version. But this issue seems to be fixed. @povderktu

**Comment by povderktu** [comment]
Alright, register the new issues, I will take a look at them in few hours! Pushing the updated version to production.
