### ISSUE TITLE
A redundant class, which isn't used anywhere

### ISSUE THREAD

**Issue by testerktu** [povderktu/cofeemachinee#6]
File : ForewordMessageProcessImpl.java
Line : -
Description : A class in the project files, which is not used at all, therefore it is redundant and should be removed from the project, to get rid of unnecessary project files.

**Comment by povderktu** [comment]
Working on solving the given issue. @testerktu

**Comment by povderktu** [comment]
Updated the project structure (removed the given unused file). Feel free to test it. @testerktu

**Comment by testerktu** [comment]
Everything seems to be fully functional. Good job on a quick fix. @povderktu

**Comment by povderktu** [comment]
That's good to hear! @testerktu 
Updating the production version.
