### ISSUE TITLE
Incorrect usage of an operator == when comparing two strings

### ISSUE THREAD

**Issue by testerktu** [povderktu/cofeemachinee#7]
File : Product.java
Line : 20
Description : Two strings are being compared using an operator == when it should be using a method called equals instead.

**Comment by povderktu** [comment]
Just fixed a similar issue few hours ago. Fixing this one as well at the moment.

**Comment by povderktu** [comment]
Test it out. @testerktu

**Comment by testerktu** [comment]
Just finished testing. Looks great. @povderktu

**Comment by povderktu** [comment]
Sounds good. Pushing it to the production version.
